### ISSUE TITLE
Context support

### ISSUE THREAD

**Issue by blacksonic** [WebReflection/uce#1]
First, thanks for this fantastic minimalistic Custom Element library!

My question is: are you planning to support a similar functionality to React/Svelte Context, where you set a value on the Context in the parent element and the value is available in child components without explicitly passing it down?
The aim would be to easily integrate `uce` components with any kind of Redux style store implementation.

**Comment by WebReflection** [comment]
you need hooks for that, so you can either check [augmentor](https://github.com/WebReflection/augmentor#available-hooks) which has a `useContext` and a `createContext`, and you augment the `render()` method on demand, or you give [hookedElements](https://github.com/WebReflection/hooked-elements#readme) a try, which also uses _augmentor_ and requires zero polyfills, plus it works very well with _µhtml_.

**Comment by WebReflection** [comment]
closing, as there's nothing to do for me here, but feel free to ask more, if needed.

**Comment by KararTY** [comment]
@WebReflection Is there an example snippet of how to use augmentor together with uce using useContext & createContext? I've attempted to follow [this](https://github.com/WebReflection/augmentor/blob/master/test/context.html) but to no avail.

I'm attempting to create a global context that's defined in a root custom element that can be fetched/updated by elements inside of the root custom element.

**Comment by WebReflection** [comment]
@KararTY [uce-template](https://github.com/WebReflection/uce-template#readme) might be the right way to go, you create a context in the top-most/outer component, and drive renders/updates through it for its nested components.

**Comment by gbishop** [comment]
I know this is old now (and closed) but this is exactly my question and I don't quite apprehend your answer. Could you point me to an example of nested components updating the state causing a render.

**Comment by gbishop** [comment]
Ah [ankar71/observed-state](https://github.com/ankar71/observed-state) is just the sort of thing I'm looking for.
