### ISSUE TITLE
usage with uland

### ISSUE THREAD

**Issue by 11111000000** [WebReflection/uce#18]
```
// @ts-ignore
import { Component, render, html, useState } from 'uland'
import { define, svg, css } from 'uce'

const Counter = Component(initialState => {
  const [count, setCount] = useState(initialState)
  return html`
    <button onclick=${() => setCount(count + 1)}>
      Count: ${count}
    </button>
  `
})

customElements.whenDefined('uce-lib').then(() => {
  define('some-widget', {
    init() {
      this.html`
        <div>
          A bounce of counters.
          <hr />
          ${Counter(0)} ${Counter(1)}
        </div>
      `
    },

    render() {
      this.html`
        <div>
          A bounce of counters.
          <hr />
          ${Counter(0)} ${Counter(1)}
        </div>
      `
    },
  })
})

```
The code above doesn't work, how do I write it correctly? i.e. I want to create a custom element that uses another (virtual) component with hooks, but it is no longer renderable. And why such fragmentation?

**Comment by WebReflection** [comment]
This is a bit upside-down ... you can always have custom elements in *uland* and anything else, literally, but you can't have *uland* components in *uce*, different libraries, different projects, different goals.

**Comment by 11111000000** [comment]
ok, I haven't read the code yet (but I will), I got the impression from the documentation that uce is a subset of uland, or uland is something like haunted for lit-element

**Comment by WebReflection** [comment]
If you want hooks, just use uhooks and bind the render once on init. uland is more like React, haunted is basically uce with hooks

**Comment by 11111000000** [comment]
Thanks!

**Comment by WebReflection** [comment]
Maybe [an example](https://codepen.io/WebReflection/pen/QWvKZEr?editors=0010) could help even more:

```js
import {define} from '//cdn.skypack.dev/uce';
import {hooked, useState} from '//cdn.skypack.dev/uhooks';

define('my-counter', {
  init() {
    this.render = hooked(this.render);
    this.render();
  },
  render() {
    const [count, setCount] = useState(0);
    this.html`
      <button @click=${() => setCount(count + 1)}>
        Clicks ${count}
      </button>`;
  }
});
```
