### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by ArthurClemens** [WebReflection/uce#4]
To use uce with TS, a types definition file would be useful. Would you be willing to add this?

**Comment by WebReflection** [comment]
I don't use TS, but I'd be more than happy to have anyone filing a PR with it 👍

**Comment by WebReflection** [comment]
P.S. check out uhtml definition, as uce exports uhtml plus `define` and nothing else 😉

**Comment by ArthurClemens** [comment]
I've just published a starter kit: https://github.com/ArthurClemens/uce-starter-typescript-rollup

I've included a proposal typing: https://github.com/ArthurClemens/uce-starter-typescript-rollup/blob/master/src/uce.d.ts#L38-L58

Usage: https://github.com/ArthurClemens/uce-starter-typescript-rollup/blob/master/src/MyCounter/index.ts#L3-L31

**Comment by WebReflection** [comment]
this is great, but there are a couple of things maybe worth changing:

  * `html` and `svg` exports, together with `render`, are exactly the same from [uhtml](https://github.com/WebReflection/uhtml/blob/master/index.d.ts)
  * the `css` *tag* always returns a string
 
### Definition

  * there is no `html` to define, it's provided out of the box in the prototype and per each instance (no `?`, `this.html` is always there)
  * the `style` must return a *string*
  * `props` and `bound` won't be part of the defined *Class*
  * any method that starts with `on` is set as event
  * any method that starts with `on` and ends with `Options` is used as event third argument

**Comment by ArthurClemens** [comment]
Thanks for the feedback. I will update the typings somewhere this week.

**Comment by ArthurClemens** [comment]
I've updated the typing, which should cover your remarks. Please let me know if things are missing.

I could not find any reference to `sharedData`, also not in the code. Perhaps this attribute has been removed?

What's left are the last 2 bullets. I don't think this can be done in TS, so it should be part of the documentation. The example counter component contains events that are described in the component interface:

```ts
interface MyCounter extends Definition<Props, OwnProps> {
  onClick: (event: Event) => void;
  onClickOptions: EventOptions;
  test: number; // some getter/setter
  method: () => string; // some method
}
```

**Comment by WebReflection** [comment]
> I could not find any reference to sharedData

what's `sharedData`? 🤔

beside that, I think this definition is pretty awesome, thanks!

Let's finalize concerns and please do MR that in here, pretty-please? Thank you!

**Comment by ArthurClemens** [comment]
Ah, `sharedData` is meant as an example: https://github.com/WebReflection/uce/blame/master/README.md#L118

But great, I'll create a PR this weekend.

**Comment by WebReflection** [comment]
well, `sharedData` is there to underline that the definition ends up in the Class prototype, like pretty much everything else, so it has no special meaning

**Comment by ArthurClemens** [comment]
Something is not right yet with the merged PR. I am getting the error `tslib.es6.js:191 Uncaught TypeError: Cannot read property 'define' of undefined`. I'll try to find what's causing this.

**Comment by WebReflection** [comment]
the usage of files in package.json broke the module .. please try latest, as the esm file wasn't there anymore

**Comment by WebReflection** [comment]
latest being `uce@1.11.6`

**Comment by ArthurClemens** [comment]
I can confirm it works now.

**Comment by gbishop** [comment]
@ArthurClemens I'd like to propose a change to index.d.ts. The names from Props should be added as members of `this` because they end up on the final class. That is, I think

```
type Render<T, U> = (
  this: {props: T} & U & { html: HTML; render: Render<T, U> } & HTMLElement,
) => unknown;
```
should be
```
type Render<T, U> = (
  this: {props: T} & T & U & { html: HTML; render: Render<T, U> } & HTMLElement,
) => unknown;
```
Note the additional instance of T in the list. The default values of Props are available in `this.props` but those don't get overwritten with attribute values from the HTML. 

Likewise in the declaration of init and This.

Am I thinking about it wrong?

**Comment by WebReflection** [comment]
I don’t TS much, so I’m ok with improvements

**Comment by ArthurClemens** [comment]
@gbishop Could you show some code where you are running into problems? Or take [uce-starter-typescript-rollup](https://github.com/ArthurClemens/uce-starter-typescript-rollup) as a starting point.

**Comment by gbishop** [comment]
For example, in uce-starter-typescript-rollup, you duplicate `count` in Props and OwnProps. You shouldn't have to do that because `define` will make `count` a property on the class if you include it in `props`.

Below is a small modification to `MyCounter/index.ts` that shows what I mean. This code works but the compiler complains about `this.count` not existing.
```
type Props = {
  count: number;
};

/**
 * Internal state and functions.
 */
type OwnProps = {
  inc: () => unknown;
  dec: () => unknown;
};

/**
 * Added Definition accessors.
 */
interface IMyCounter extends Definition<Props, OwnProps> {
  onClick: (event: Event) => void;
  onClickOptions: EventOptions;
  test: number; // some getter/setter
  method: () => string; // some method
}

export const MyCounter: IMyCounter = {
  props: {
    count: 0
  },
  init: function () {
    this.dec = () => {
      this.count--;
      this.render();
    };
    this.inc = () => {
      this.count++;
      this.render();
    };
    this.classList.add('my-prefix');
    this.render();
  },
```
The following change to `uce/index.d.ts` fixes the type complaints:

```
$ diff types/uce/index.d.ts node_modules/uce/index.d.ts
5c5
<   this: {props: T} & T & U & { html: HTML; render: Render<T, U> } & HTMLElement,
---
>   this: {props: T} & U & { html: HTML; render: Render<T, U> } & HTMLElement,
7c7
< type This<T, U> = { props: T } & T & U & {
---
> type This<T, U> = { props: T } & U & {
73c73
<     this: { props: T } & T & U & HTMLElement & { html: HTML; render: Render<T, U> },
---
>     this: { props: T } & U & HTMLElement & { html: HTML; render: Render<T, U> },
```

**Comment by WebReflection** [comment]
Could this be more generic and a PR?

**Comment by gbishop** [comment]
I'll be glad to make a pull request. I don't know what you mean by more
generic.

**Comment by WebReflection** [comment]
> I don't know what you mean by more generic.

I mean ... `props` can be anything, or even `null`, so the current `type Props` is not portable.

**Comment by gbishop** [comment]
We'll only get strings handed in from HTML. I'm not skilled enough at TypeScript to know how to require all the members of `props` to be of type string. I'm not even sure we'd want to since [test/props.html](https://github.com/WebReflection/uce/blob/master/test/props.html), for example, treats it like a number and javascript allows you to get away with it. 

Can you write a rule that says `T` and thus `props` that has type `T` can only contain strings?

I'm actually working in Javascript and using tsserver for type checking. I find that more pleasant than some of the duplication required by typescript.

**Comment by WebReflection** [comment]
Imagine I don't TS at all and never cared much about TS 😅 ... everything TS in my repos is either JSDoc like or contributors 🥳

**Comment by gbishop** [comment]
Arthur's definition allows for props to be anything. They just need a declaration. You could even declare `count` to be `number | string` to handle strings coming in and numbers in use. I'd be more likely to make them OwnProps (that is not set by HTML) if they had types other than strings.
