### ISSUE TITLE
Inject style into ShadowDOM if attached

### ISSUE THREAD

**Issue by davidbwaters** [WebReflection/uce#8]
Shouldn't style inject into the shadow, if attached, and selector could just be `:host`, and inject into the head like it does now otherwise.

**Comment by WebReflection** [comment]
Sorry for coming back so late, I've missed this issue somehow.

If you have shadow DOM you're likely going to render there, hence put your style within the render right away.

If I put that style instead, you'll likely trash it, as you wouldn't expect the shadowRoot to be already populated.

In few words, the `style` utility here is for global styles per class/component, what you render within your shdowRoot is up to you, including styles with `:host`.

I hope this makes sense, and maybe I could specify this better in the README.

**Comment by davidbwaters** [comment]
yeah, i was just thinking as sugar, if you wanted to separate styles in the class, and since style wouldn't be otherwise useful for shadow components.

**Comment by davidbwaters** [comment]
and no worries, you're maintaining like a million packages haha.

**Comment by WebReflection** [comment]
It’s error prone, the moment you render on the ShadowDOM, whatever magic I’ll do will be lost. This is a foot gum, not a helper, so I’m ok improving README (which I did) or documentation, I’m not willing to explain the footgun to anyone thinking a render will keep style around in the ShadowDOM. You are in control, it’s not a matter of maintaining this, it’s a matter of avoiding too much magic that would easily backfire. Current way is static, once, per definition, not some unexpected shadow root node.
