### ISSUE TITLE
uce-template Custom Element slots in plain uce

### ISSUE THREAD

**Issue by bb010g** [WebReflection/uce#9]
[uce-template](https://github.com/WebReflection/uce-template) provides a helper for initializing custom elements from their initial content named `slot`:

https://github.com/WebReflection/uce-template/blob/bdf398340dbb9f60309663e131b2c011c2e5ddb4/esm/index.js#L77-L103
```js
const queryHelper = (attr, arr) => element => {
  return [].reduce.call(
    element.querySelectorAll('[' + attr + ']'),
    (slot, node) => {
      let {parentNode} = node;
      do {
        if (parentNode === element) {
          const name = get(node, attr);
          slot[name] = arr ? [].concat(slot[name] || [], node) : node;
          break;
        }
        else if (/-/.test(parentNode.tagName) || get(parentNode, 'is'))
          break;
      } while (parentNode = parentNode.parentNode);
      return slot;
    },
    {}
  );
};


// preloaded imports
const virtualNameSpace = {
  define, render, html, svg, css,
  reactive: stateHandler({useState}),
  ref: queryHelper('ref', false),
  slot: queryHelper('slot', true)
};
```

Would you recommend replicating this helper for use with plain `uce` or using another method? (If the former, could `slot` be added to a future `uce` release?)

**Comment by WebReflection** [comment]
do you mean as an export or as internal utility? although, as uce-template uses uce, I guess it makes sense to move those helpers in uce and export these so that uce-template can use these too ... or you were thinking about something else?

anyway, will think about this, it might be handy in uce too.

**Comment by bb010g** [comment]
I was thinking about moving the helpers' functionalities into `uce` from `uce-template`, and then providing that through uce's API in whatever manner is most natural, ideally so `uce-template`'s `ref` & `slot` could reuse `uce`'s implementations.

**Comment by WebReflection** [comment]
btw, reactive is already a module a part, and I don't want to bloat uce wih uhooks, so that's not going to happen, because it's already possible, see https://github.com/WebReflection/reactive-props#readme

**Comment by WebReflection** [comment]
could you please try to `import {slot} from 'uce-helpers'` ? it exports `slot`, `ref`, `get`, and `has` from *uce-template* and I need to put a README and some test that makes sense but it's the same code.

This way uce-template can depend on it, and you're free to use the same helpers too with *uce*.

This doesn't affect *uce* at all, i actually gives you the freedom to import, or not, those helpers, whenever it's needed.

I hope this works fine.

**Comment by bb010g** [comment]
That sounds like a great solution; thank you!

**Comment by WebReflection** [comment]
It's up and running (travis a part ... today travis doesn't run at all ...)

https://github.com/WebReflection/uce-helpers#readme

uce-template has been update to use it too ... if nothing, it's 100% test-covered
